# Compilers

c_compiler:
  - clang                         # [osx]
  - gcc                           # [linux]
cxx_compiler:
  - clangxx                       # [osx]
  - gxx                           # [linux]
fortran_compiler:
  - gfortran
target_platform:
  - osx-64                        # [osx]
  - linux-64                      # [linux]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk           # [osx]

# Packages
blas:
  - 2.15
mkl:
  - 2019.0
eigen:
  - 3.3.7
mkl_static:
  - 2019.0
mkl_include:
  - 2019.0
intel_openmp:
  - 2019.0
cmake:
  - 3.14.0
python:
  - 3.6
  - 3.7
  - 3.8
numpy:
  - 1.18.1
openmp:
  - 8.0.1
